jobs:
- job: build_osx_10_13_xcode10_1
  pool:
    vmImage: 'macOS-10.13'
  variables:
    DEVELOPER_DIR: "/Applications/Xcode_10.1.app"
  steps:
  - script: brew install libtool automake
    displayName: brew install
  - script: |
      cd Chapter01/gradle
      ./gradlew test -Pconfig=Debug
      ./gradlew build_all -Pconfig=Release
      cd ../..
      cd ChapterXX/gradle
      ./gradlew test -Pconfig=Debug
      ./gradlew build_all -Pconfig=Release
      cd ../..
    env:
      AZURE_STORAGE_ACCOUNT: $(azure.storage.account)
      AZURE_STORAGE_KEY: $(azure.storage.key)
      AZURE_STORAGE_CONTAINER_NAME: $(azure.storage.container.name)
      ORG_GRADLE_PROJECT_renew_cache: $(cache.renew)
    displayName: build all
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/Chapter01/build_release/Release'
      artifactName: vst3samplehost_release_osx_10_13_xcode10_1_chapter01
    displayName: publish chapter01
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/ChapterXX/build_release/Release'
      artifactName: vst3samplehost_release_osx_10_13_xcode10_1_chapterXX
    displayName: publish chapterXX
- job: build_win_msvc_2017
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      cd Chapter01/gradle
      call gradlew test -Pconfig=Debug
      call gradlew build_all -Pconfig=Release
      cd ../..
      cd ChapterXX/gradle
      call gradlew test -Pconfig=Debug
      call gradlew build_all -Pconfig=Release
      cd ../..
    env:
      AZURE_STORAGE_ACCOUNT: $(azure.storage.account)
      AZURE_STORAGE_KEY: $(azure.storage.key)
      AZURE_STORAGE_CONTAINER_NAME: $(azure.storage.container.name)
      ORG_GRADLE_PROJECT_renew_cache: $(cache.renew)
    displayName: build all
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/Chapter01/build_release/Release'
      artifactName: vst3samplehost_release_win_msvc2017_chapter01
    displayName: "publish chapter01"
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(System.DefaultWorkingDirectory)/ChapterXX/build_release/Release'
      artifactName: vst3samplehost_release_win_msvc2017_chapterXX
    displayName: "publish chapterXX"
