trigger:
- '*'
pr:
- '*'
jobs:
- job: build_osx_10_13_xcode10_1
  pool:
    vmImage: 'macOS-10.13'
  variables:
    DEVELOPER_DIR: "/Applications/Xcode_10.1.app"
  steps:
  - script: brew install libtool automake
    displayName: brew install
  - script: |
      cd gradle
      ./gradlew test_all -Pconfig=Debug
      ./gradlew build_all -Pconfig=Release
      cd ..
    env:
      AZURE_STORAGE_ACCOUNT: $(azure.storage.account)
      AZURE_STORAGE_KEY: $(azure.storage.key)
      AZURE_STORAGE_CONTAINER_NAME: $(azure.storage.container.name)
      ORG_GRADLE_PROJECT_renew_cache: $(cache.renew)
    displayName: build all
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.DefaultWorkingDirectory)/build_release/Release'
      contents:  '**'
      targetFolder: '$(Build.ArchiveStagingDirectory)'
    displayName: Copy binaries
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArchiveStagingDirectory)'
      artifactName: vst3samplehost_release_osx_xcode10_1
    displayName: publish artifacts
- job: build_win_msvc_2017
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
      cd gradle
      call gradlew test_all -Pconfig=Debug -Pmsvc_version="Visual Studio 15 2017" -Pcache_title=win2016-vs2017 || exit /b
      call gradlew build_all -Pconfig=Release -Pmsvc_version="Visual Studio 15 2017" -Pcache_title=win2016-vs2017 || exit /b
      cd ..
    env:
      AZURE_STORAGE_ACCOUNT: $(azure.storage.account)
      AZURE_STORAGE_KEY: $(azure.storage.key)
      AZURE_STORAGE_CONTAINER_NAME: $(azure.storage.container.name)
      ORG_GRADLE_PROJECT_renew_cache: $(cache.renew)
    displayName: build all
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.DefaultWorkingDirectory)/build_release/Release'
      contents:  '**'
      targetFolder: '$(Build.ArchiveStagingDirectory)'
    displayName: Copy binaries
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArchiveStagingDirectory)'
      artifactName: vst3samplehost_release_win_msvc2017
    displayName: publish artifacts
- job: build_win_msvc_2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - script: |
      cd gradle
      call gradlew test_all -Pconfig=Debug -Pmsvc_version="Visual Studio 16 2019" -Pcache_title=win2019-vs2019 || exit /b
      call gradlew build_all -Pconfig=Release -Pmsvc_version="Visual Studio 16 2019" -Pcache_title=win2019-vs2019 || exit /b
      cd ..
    env:
      AZURE_STORAGE_ACCOUNT: $(azure.storage.account)
      AZURE_STORAGE_KEY: $(azure.storage.key)
      AZURE_STORAGE_CONTAINER_NAME: $(azure.storage.container.name)
      ORG_GRADLE_PROJECT_renew_cache: $(cache.renew)
    displayName: build all
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(System.DefaultWorkingDirectory)/build_release/Release'
      contents:  '**'
      targetFolder: '$(Build.ArchiveStagingDirectory)'
    displayName: Copy binaries
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArchiveStagingDirectory)'
      artifactName: vst3samplehost_release_win_msvc2019
    displayName: publish artifacts
